### PR TITLE
**BREAKING** Type Stability for MOInputs

### PR DESCRIPTION
**Pull request by willtebbutt**
**Summary**

Make input collection types for isotopic multi-output things type stable.

**Proposed changes**

Change the `Integer` type constraint in `MOInputIsotopicByFeatures` and `MOInputIsotopicByOutputs` with`Int`s.

**What alternatives have you considered?**

Could have parametrised the type to allow any `Integer`, but I think this is probably fine.

**Breaking changes**

If anyone is currently using anything other than an `Int` to specify the number of outputs, they'll need to change it to an `Int`. I can't imagine that this happens very often, so effects should be minimal.

### CODE REVIEW

**Comment by st--** [comment]
Seems fine to me.
For the doc issue, you need to update the Manifests of doc/ and examples/*/.
For the test issue, see https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/pull/409

**Review by theogf — APPROVED** [review]

**Comment by willtebbutt** [comment]
@theogf @st-- there are a number of other things that we've wanted to address in the next breaking release for a while: https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/issues/338

I don't have time to push these through right now, so I'm going to hold off on merging this until we've got them in place either in this PR or another, so that we don't have to block patch releases on master.

**Comment by theogf** [comment]
Should be generally have a branch `breaking_master` where we can merge these breaking PRs?

**Comment by willtebbutt** [comment]
Closed in favour of #465 , which is non-breaking

**Pull request closed without merging**
