### PR TITLE
Cancel previous running workflows on push

### PR DESCRIPTION
**Pull request by devmotion**
Just learnt about https://github.com/styfle/cancel-workflow-action from https://github.com/JuliaDiff/ChainRules.jl/issues/426. Seems this could solve https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/issues/281.

I followed the instructions in https://github.com/styfle/cancel-workflow-action#advanced-pull-requests-from-forks which should also work for PRs from forks.

### CODE REVIEW

**Comment by mzgubic** [comment]
It doesn't seem like it ran, did it?

**Comment by devmotion** [comment]
IIRC this type of actions always uses the version on master for security reasons. It doesn't exist currently so it's not run.

**Comment by devmotion** [comment]
It is mentioned in the [documentation](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_run):

> Note: This event will only trigger a workflow run if the workflow file is on the default branch.

**Comment by devmotion** [comment]
Of course, this makes it difficult to assess if the action works properly here :smile: 

@willtebbutt @theogf What do you think, should we just try it and see if it works and possibly fix it in follow-up PRs?

**Review by willtebbutt — APPROVED** [review]
Yeah, let's do it, 🤞

**Comment by theogf** [comment]
Go for it!

**Comment by devmotion** [comment]
It seems to be at least somewhat correct and working: https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/actions/runs/897590843

**Pull request merged**
