### PR TITLE
MOInput Type Stability

### PR DESCRIPTION
**Pull request by willtebbutt**
**Summary**
Makes the type of `out_dim` field of `MOInput` a type parameter of `MOInput`. This has been done in a non-breaking way.

**Proposed changes**

See summary

* ...

**What alternatives have you considered?**

https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/pull/405 consides an alternative approach in which the type is constrained to `Int`. This has the disadvantage of being more constrained, and constituting a break change. The potential advantage over the approach used here is slight changes in compile time, but my instinct is that these will be negligible.

**Breaking changes**

None

### CODE REVIEW

**Comment by theogf** [comment]
Maybe add a @inferred test?

**Comment by willtebbutt** [comment]
@theogf done!

**Review by theogf — APPROVED** [review]

**Comment by willtebbutt** [comment]
Thanks for the swift review @theogf  -- will merge when CI passes

**Comment by willtebbutt** [comment]
@theogf looks like Others on 1.3 is failing on the doctests -- the formatting of the type printing appears to be different for that version. I don't know how tests were passing previously, because presumably this hasn't changed... 😬 

Any thoughts?

**Comment by theogf** [comment]
Probably the doctestfilter don't catch so many types or something? Didn't we mention dropping 1.3 anyways?

**Comment by willtebbutt** [comment]
Cool. I'm just going to drop CI for 1.3

**Comment by willtebbutt** [comment]
@theogf any idea how I tell github to not require the 1.3 tests to be run?

**Pull request merged**
