### PR TITLE
Fix Independent MOKernel for single dimension input

### PR DESCRIPTION
**Pull request by sharanry**
Fails for 
```julia
N = 100
x = rand(Uniform(-1, 1), N)
X = MOInput(x, 2)
k = IndependentMOKernel(MaternKernel())
k(X, X) #error
```

### CODE REVIEW

**Comment by theogf** [comment]
Nice catch! Could you also add a test for this?

**Comment by sharanry** [comment]
@theogf Is this fine?

**Comment by theogf** [comment]
Looks good! You can use `@test_nothrow` instead of checking for a matrix type

**Comment by devmotion** [comment]
> You can use @test_nothrow instead of checking for a matrix type

Is this a custom thing we define in KernelFunctions? I have never seen it in Base :thinking: IMO you could just remove `@test_nothrow` - if the call errors, the tests fail anyways.

**Comment by sharanry** [comment]
> > You can use @test_nothrow instead of checking for a matrix type
> 
> Is this a custom thing we define in KernelFunctions? I have never seen it in Base thinking IMO you could just remove `@test_nothrow` - if the call errors, the tests fail anyways.

I think `@test_nothrows` helps by catching the error and letting the other tests after it run irrespective of whether the error occurs.

**Comment by theogf** [comment]
I am sorry! I am at the beach so i did not double check :sweat_smile:. I meant `@test_nowarn`

**Comment by willtebbutt** [comment]
Wait, @sharanry could you explain to me why this is failing? I'm unclear why the previous implementation is incorrect 😬 .

In particular, why is the solution you've implemented the correct one?

**Comment by sharanry** [comment]
Previously, `(κ::IndependentMOKernel)` worked with only inputs of the type `Tuple{Vector, Int}`. However, when working with 1-dim inputs, we might end up with `Tuple{<:Real, Int}` which wouldn't have been accepted by the old implementation.

**Comment by willtebbutt** [comment]
Oh, I see. Would the following not be sufficient:
```julia
function (k::IndependentMOKernel)(x::Tuple{Any, Int}, y::Tuple{Any, Int})
    if last(x) == last(y)
        return k.kernel(first(x), first(y))
    else
        return appropriate_zero
    end
end
```

i.e. I'm not sure that we need two methods, or to assume that the wrapped kernel requires vector inputs.

**Comment by sharanry** [comment]
That should be sufficient. However, we wouldn't have any checks for the first element of the tuple as you point out. I like it as it is definitely a less constrained way. 

Shall I start a new PR for this?

**Comment by willtebbutt** [comment]
> That should be sufficient. However, we wouldn't have any checks for the first element of the tuple as you point out. I like it as it is definitely a less constrained way.

Do we need a check on the type of the first element of the tuples? Can they not generally be anything?

> Shall I start a new PR for this?

That would be good -- better to address this sooner rather than later :)

**Comment by sharanry** [comment]
> Do we need a check on the type of the first element of the tuples? Can they not generally be anything?

I guess not. This is should make the kernels more flexible. For other non-multi-output kernels we do not really perform any check for the inputs.

**Pull request merged**
