### PR TITLE
Fix method ambiguities

### LINKED ISSUE #481: Ambiguities
We actually have quite a lot of method ambiguities:
```julia
julia> using KernelFunctions, Test

julia> Test.detect_ambiguities(KernelFunctions)
20-element Vector{Tuple{Method, Method}}:
 (pairwise(d::Distances.PreMetric, x::AbstractVector{<:Real}, y::AbstractVector{<:Real}) in KernelFunctions at /Users/willtebbutt/.julia/packages/KernelFunctions/02rTu/src/distances/pairwise.jl:19, pairwise(d::Distances.PreMetric, x::ColVecs, y::AbstractVector) in KernelFunctions at /Users/willtebbutt/.julia/packages/KernelFunctions/02rTu/src/utils.jl:107)
 (pairwise(d::Distances.PreMetric, x::AbstractVector{<:Real}, y::AbstractVector{<:Real}) in KernelFunctions at /Users/willtebbutt/.julia/packages/KernelFunctions/02rTu/src/distances/pairwise.jl:19, pairwise(d::Distances.PreMetric, x::AbstractVector, y::RowVecs) in KernelFunctions at /Users/willtebbutt/.julia/packages/KernelFunctions/02rTu/src/utils.jl:175)
 (frule(::ChainRulesCore.RuleConfig, args...) in ChainRulesCore at /Users/willtebbutt/.julia/packages/ChainRulesCore/C73ay/src/rules.jl:64, frule(::Any, d::Distances.Euclidean, x::AbstractVector, y::AbstractVector) in KernelFunctions at /Users/willtebbutt/.julia/packages/KernelFunctions/02rTu/src/chainrules.jl:4)
 (+(k::Kernel, ks::KernelSum) in KernelFunctions at /Users/willtebbutt/.julia/packages/KernelFunctions/02rTu/src/kernels/overloads.jl:16, +(ks::KernelSum{<:AbstractVector{<:Kernel}}, k::Kernel) in KernelFunctions at /Users/willtebbutt/.julia/packages/KernelFunctions/02rTu/src/kernels/overloads.jl:20)
 (tensor(k::Kernel, ks::KernelTensorProduct{<:AbstractVector{<:Kernel}}) in KernelFunctions at /Users/willtebbutt/.julia/packages/KernelFunctions/02rTu/src/kernels/overloads.jl:17, tensor(ks::KernelTensorProduct, k::Kernel) in KernelFunctions at /Users/willtebbutt/.julia/packages/KernelFunctions/02rTu/src/kernels/overloads.jl:19)
 (tensor(k1::KernelTensorProduct, k2::KernelTensorProduct) in KernelFunctions at /Users/willtebbutt/.julia/packages/KernelFunctions/02rTu/src/kernels/overloads.jl:9, tensor(k::Kernel, ks::KernelTensorProduct{<:AbstractVector{<:Kernel}}) in KernelFunctions at /Users/willtebbutt/.julia/packages/KernelFunctions/02rTu/src/kernels/overloads.jl:17)
 (map(f::Tf, A::SparseArrays.SparseVector) where Tf in SparseArrays.HigherOrderFns at /Users/willtebbutt/.julia/juliaup/julia-1.8.2+0.x64/share/julia/stdlib/v1.8/SparseArrays/src/higherorderfns.jl:147, map(t::Transform, x::AbstractVector) in KernelFunctions at /Users/willtebbutt/.julia/packages/KernelFunctions/02rTu/src/transform/transform.jl:11)
 (tensor(k::Kernel, ks::KernelTensorProduct) in KernelFunctions at /Users/willtebbutt/.julia/packages/KernelFunctions/02rTu/src/kernels/overloads.jl:16, tensor(ks::KernelTensorProduct{<:AbstractVector{<:Kernel}}, k::Kernel) in KernelFunctions at /Users/willtebbutt/.julia/packages/KernelFunctions/02rTu/src/kernels/overloads.jl:20)
 (*(k::Kernel, ks::KernelProduct) in KernelFunctions at /Users/willtebbutt/.julia/packages/KernelFunctions/02rTu/src/kernels/overloads.jl:16, *(ks::KernelProduct{<:AbstractVector{<:Kernel}}, k::Kernel) in KernelFunctions at /Users/willtebbutt/.julia/packages/KernelFunctions/02rTu/src/kernels/overloads.jl:20)
 (*(k1::KernelProduct, k2::KernelProduct) in KernelFunctions at /Users/willtebbutt/.julia/packages/KernelFunctions/02rTu/src/kernels/overloads.jl:9, *(ks::KernelProduct{<:AbstractVector{<:Kernel}}, k::Kernel) in KernelFunctions at /Users/willtebbutt/.julia/packages/KernelFunctions/02rTu/src/kernels/overloads.jl:20)
 (tensor(k1::KernelTensorProduct, k2::KernelTensorProduct) in KernelFunctions at /Users/willtebbutt/.julia/packages/KernelFunctions/02rTu/src/kernels/overloads.jl:9, tensor(ks::KernelTensorProduct{<:AbstractVector{<:Kernel}}, k::Kernel) in KernelFunctions at /Users/willtebbutt/.julia/packages/KernelFunctions/02rTu/src/kernels/overloads.jl:20)
 (+(k1::KernelSum, k2::KernelSum) in KernelFunctions at /Users/willtebbutt/.julia/packages/KernelFunctions/02rTu/src/kernels/overloads.jl:9, +(k::Kernel, ks::KernelSum{<:AbstractVector{<:Kernel}}) in KernelFunctions at /Users/willtebbutt/.julia/packages/KernelFunctions/02rTu/src/kernels/overloads.jl:17)
 (+(k1::KernelSum, k2::KernelSum) in KernelFunctions at /Users/willtebbutt/.julia/packages/KernelFunctions/02rTu/src/kernels/overloads.jl:9, +(ks::KernelSum{<:AbstractVector{<:Kernel}}, k::Kernel) in KernelFunctions at /Users/willtebbutt/.julia/packages/KernelFunctions/02rTu/src/kernels/overloads.jl:20)
 (+(k::Kernel, ks::KernelSum{<:AbstractVector{<:Kernel}}) in KernelFunctions at /Users/willtebbutt/.julia/packages/KernelFunctions/02rTu/src/kernels/overloads.jl:17, +(ks::KernelSum, k::Kernel) in KernelFunctions at /Users/willtebbutt/.julia/packages/KernelFunctions/02rTu/src/kernels/overloads.jl:19)
 (*(k1::KernelProduct, k2::KernelProduct) in KernelFunctions at /Users/willtebbutt/.julia/packages/KernelFunctions/02rTu/src/kernels/overloads.jl:9, *(k::Kernel, ks::KernelProduct{<:AbstractVector{<:Kernel}}) in KernelFunctions at /Users/willtebbutt/.julia/packages/KernelFunctions/02rTu/src/kernels/overloads.jl:17)
 (pairwise(d::Distances.PreMetric, x::AbstractVector{<:Real}, y::AbstractVector{<:Real}) in KernelFunctions at /Users/willtebbutt/.julia/packages/KernelFunctions/02rTu/src/distances/pairwise.jl:19, pairwise(d::Distances.PreMetric, x::AbstractVector, y::ColVecs) in KernelFunctions at /Users/willtebbutt/.julia/packages/KernelFunctions/02rTu/src/utils.jl:104)
 (∘(t::Transform, tc::ChainTransform) in KernelFunctions at /Users/willtebbutt/.julia/packages/KernelFunctions/02rTu/src/transform/chaintransform.jl:37, ∘(tc::ChainTransform, t::Transform) in KernelFunctions at /Users/willtebbutt/.julia/packages/KernelFunctions/02rTu/src/transform/chaintransform.jl:38)
 (pairwise(d::Distances.PreMetric, x::AbstractVector{<:Real}, y::AbstractVector{<:Real}) in KernelFunctions at /Users/willtebbutt/.julia/packages/KernelFunctions/02rTu/src/distances/pairwise.jl:19, pairwise(d::Distances.PreMetric, x::RowVecs, y::AbstractVector) in KernelFunctions at /Users/willtebbutt/.julia/packages/KernelFunctions/02rTu/src/utils.jl:178)
 (*(k::Kernel, ks::KernelProduct{<:AbstractVector{<:Kernel}}) in KernelFunctions at /Users/willtebbutt/.julia/packages/KernelFunctions/02rTu/src/kernels/overloads.jl:17, *(ks::KernelProduct, k::Kernel) in KernelFunctions at /Users/willtebbutt/.julia/packages/KernelFunctions/02rTu/src/kernels/overloads.jl:19)
 (map(f::Tf, A::Union{SparseArrays.AbstractSparseMatrixCSC, SparseArrays.SparseVector}, Bs::Vararg{Union{SparseArrays.AbstractSparseMatrixCSC, SparseArrays.SparseVector}, N}) where {Tf, N} in SparseArrays.HigherOrderFns at /Users/willtebbutt/.julia/juliaup/julia-1.8.2+0.x64/share/julia/stdlib/v1.8/SparseArrays/src/higherorderfns.jl:151, map(t::Transform, x::AbstractVector) in KernelFunctions at /Users/willtebbutt/.julia/packages/KernelFunctions/02rTu/src/transform/transform.jl:11)
```
We should probably resolve these, and add a test to prevent new ones creeping in.

### PR DESCRIPTION
**Pull request by devmotion**
Fixes #481.

~~I assume the only questionable change is that fixing the method ambiguity of `map(t::Transform, ::AbstractVector)`, caused by `map(::Tf, ::SparseVector) where {Tf}` in SparseArrays, requires adding a dependency on SparseArrays.~~

### CODE REVIEW

**Comment by devmotion** [comment]
> I assume the only questionable change is that fixing the method ambiguity of `map(t::Transform, ::AbstractVector)`, caused by `map(::Tf, ::SparseVector) where {Tf}` in SparseArrays, requires adding a dependency on SparseArrays.

I guess it's even more questionable since actually it is not sufficient to fix the method ambiguities in the tests which load additional packages (see, e.g., https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/actions/runs/3268189406/jobs/5374299901#step:6:222 and https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/actions/runs/3268189406/jobs/5374301250#step:6:224):
```julia
   Evaluated: isempty(Tuple{Method, Method}[(map(f::Tf, A::SparseArrays.AbstractCompressedVector) where Tf @ SparseArrays.HigherOrderFns /opt/hostedtoolcache/julia/nightly/x64/share/julia/stdlib/v1.9/SparseArrays/src/higherorderfns.jl:152, map(t::Transform, x::AbstractVector) @ KernelFunctions ~/work/KernelFunctions.jl/KernelFunctions.jl/src/transform/transform.jl:11), (map(f, A::NamedDims.NamedDimsArray) @ NamedDims ~/.julia/packages/NamedDims/kCxfn/src/functions.jl:157, map(t::Transform, x::AbstractVector) @ KernelFunctions ~/work/KernelFunctions.jl/KernelFunctions.jl/src/transform/transform.jl:11), (map(f, a1::StaticArraysCore.StaticArray, as::AbstractArray...) @ StaticArrays ~/.julia/packages/StaticArrays/PUoe1/src/mapreduce.jl:30, map(t::Transform, x::AbstractVector) @ KernelFunctions ~/work/KernelFunctions.jl/KernelFunctions.jl/src/transform/transform.jl:11), (map(f, As::AxisArray{T, N, D, Ax}...) where {T, N, D, Ax<:Tuple{Vararg{Axis}}} @ AxisArrays ~/.julia/packages/AxisArrays/v7vf4/src/core.jl:431, map(t::Transform, x::AbstractVector) @ KernelFunctions ~/work/KernelFunctions.jl/KernelFunctions.jl/src/transform/transform.jl:11), (map(f, A::AxisArray) @ AxisArrays ~/.julia/packages/AxisArrays/v7vf4/src/core.jl:422, map(t::Transform, x::AbstractVector) @ KernelFunctions ~/work/KernelFunctions.jl/KernelFunctions.jl/src/transform/transform.jl:11), (map(f::Tf, A::Union{SparseArrays.AbstractCompressedVector, SparseArrays.AbstractSparseMatrixCSC}, Bs::Vararg{Union{SparseArrays.AbstractCompressedVector, SparseArrays.AbstractSparseMatrixCSC}, N}) where {Tf, N} @ SparseArrays.HigherOrderFns /opt/hostedtoolcache/julia/nightly/x64/share/julia/stdlib/v1.9/SparseArrays/src/higherorderfns.jl:156, map(t::Transform, x::AbstractVector) @ KernelFunctions ~/work/KernelFunctions.jl/KernelFunctions.jl/src/transform/transform.jl:11)])
```

**Comment by devmotion** [comment]
So I am not sure if we can fix the `map` method ambiguity issues at all.

**Comment by theogf** [comment]
@devmotion Can we get this merged anyway (we can leave some ambiguities)

**Review by theogf — APPROVED** [review]

**Comment by theogf** [comment]
Lgtm when the tests are fixed

**Comment by devmotion** [comment]
@theogf I managed to fix all method ambiguities by completely removing the definition of `map(t::Transform, x::AbstractVector)` (causes problems with basically every array package since they tend to implement `map(f, x::MyArray)`). Instead I only defined `map(t::Transform, x::Union{ColVecs,RowVecs})`.

**Pull request merged**
