### PR TITLE
Example notebook: training kernel parameters

### PR DESCRIPTION
**Pull request by st--**

### CODE REVIEW

**Comment by willtebbutt** [comment]
@st-- how would you like to progress with this PR? The example generally looks reasonable to me, so I'm happy to review it for details if that's what you'd like. Just wondering if there's any specific kind of feedback that you're interested in.

**Comment by Crown421** [comment]
I have finally managed to work on this and have something that could be nice. I am not sure if I can push to this PR, or should/need to open a new one?

**Comment by willtebbutt** [comment]
I would imagine it would be safer to implement in a new PR, unless @st-- thinks otherwise?

**Comment by st--** [comment]
#430 is much better, thanks @Crown421 !

**Pull request closed without merging**
